version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=bookmark1
    ports:
      - '3001:3000'

  app2:
    build: .
    environment:
      - APP_NAME=bookmark2
    ports:
      - '3002:3000'

  app3:
    build: .
    environment:
      - APP_NAME=bookmark3
    ports:
      - '3003:3000'

  nginx:
    build:
      context: ./nginx-docker
    ports:
      - '8080:8080'
    depends_on:
      - app1
      - app2
      - app3
